### ISSUE TITLE
Server immediately crashes after installation

### ISSUE THREAD

**Issue by object-Object** [omnilib/vscode-ufmt#38] opened 2022-11-20 21:02 UTC
Installed the ufmt extension and immediately got the message "The ufmt server crashed 5 times in the last 3 minutes. The server will not be restarted."

Using a Python 3.11.0 workspace with a venv, extension version `v2022.9.14`.

Error message from the Output tab:
```
Traceback (most recent call last):
  File "c:\Users\jack\.vscode\extensions\omnilib.ufmt-2022.9.14-win32-x64\bundled\tool\server.py", line 45, in <module>
    from pygls import lsp, protocol, server, uris, workspace
  File "c:\Users\jack\.vscode\extensions\omnilib.ufmt-2022.9.14-win32-x64\bundled\libs\pygls\lsp\__init__.py", line 23, in <module>
    from pygls.lsp.types import *
  File "c:\Users\jack\.vscode\extensions\omnilib.ufmt-2022.9.14-win32-x64\bundled\libs\pygls\lsp\types\__init__.py", line 6, in <module>
    from pygls.lsp.types.general_messages import *
  File "c:\Users\jack\.vscode\extensions\omnilib.ufmt-2022.9.14-win32-x64\bundled\libs\pygls\lsp\types\general_messages.py", line 35, in <module>
    from pygls.lsp.types.language_features import (CallHierarchyClientCapabilities,
  File "c:\Users\jack\.vscode\extensions\omnilib.ufmt-2022.9.14-win32-x64\bundled\libs\pygls\lsp\types\language_features\__init__.py", line 2, in <module>
    from pygls.lsp.types.language_features.call_hierarchy import *
  File "c:\Users\jack\.vscode\extensions\omnilib.ufmt-2022.9.14-win32-x64\bundled\libs\pygls\lsp\types\language_features\call_hierarchy.py", line 70, in <module>
    class CallHierarchyIncomingCall(Model):
  File "c:\Users\jack\.vscode\extensions\omnilib.ufmt-2022.9.14-win32-x64\bundled\libs\pydantic\main.py", line 292, in __new__
    cls.__signature__ = ClassAttribute('__signature__', generate_model_signature(cls.__init__, fields, config))
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\jack\.vscode\extensions\omnilib.ufmt-2022.9.14-win32-x64\bundled\libs\pydantic\utils.py", line 258, in generate_model_signature
    merged_params[param_name] = Parameter(
                                ^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\inspect.py", line 2715, in __init__
    raise ValueError('{!r} is not a valid parameter name'.format(name))
ValueError: 'from' is not a valid parameter name
```

**Comment by trankov** [comment] 2023-01-09 16:18
As far as I've investigate the issue, the reason is in outdated Pydantic version in extension's bundle. So the solution is to replace Pydantic folder with a fresh one. It's a bit hacky of course, but works at the moment. Hope it'll be fixed soon.

**Comment by amyreese** [comment] 2023-12-27 08:48
Hi, apologies for not following up on this sooner. I haven't been able to replicate this issue in any recent releases, so I'm going to close this issue. Please feel free to comment here or open a new issue if you are able to reproduce this on the latest (today's) release. Cheers!

**Closed by amyreese** 2023-12-27 08:48 UTC
